name: CICD
on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create PEM File
        run: |
          echo "${{ secrets.DEPLOY_EC2_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Deploy to EC2
        env:
          DEPLOY_EC2_HOST: ${{ secrets.DEPLOY_EC2_HOST }}
          DEPLOY_EC2_USER: ${{ secrets.DEPLOY_EC2_USER }}
        run: |
            ssh -i deploy_key.pem -o StrictHostKeyChecking=no $DEPLOY_EC2_USER@$DEPLOY_EC2_HOST
            cd /home/ubuntu/reactjs-app
            git pull origin deploy-to-ec2
            sudo docker build -t react-app .
            sudo docker run -d -p 3000:80 --name react-app react-app


