name: CICD
on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_EC2_HOST }}
          username: ${{ secrets.DEPLOY_EC2_USER }}
          key: ${{ secrets.DEPLOY_EC2_KEY }}
          port: 2222
          command_timeout: 30m
          script: | 
            echo "Nice Job!!!"
        env:
          DEPLOY_EC2_HOST: ${{ secrets.DEPLOY_EC2_HOST }}
          DEPLOY_EC2_USER: ${{ secrets.DEPLOY_EC2_USER }}
        run: |
            cd /home/ubuntu/reactjs-app
            git pull origin deploy-to-ec2
            sudo docker build -t react-app .
            sudo docker run -d -p 3000:80 --name react-app react-app


